export 'home/home_screen.dart';
export 'home/details_screen.dart';
export 'register_screen.dart';
export 'dashboard_screen.dart';
export 'appointment/myappoinment_screen.dart';
export 'profile/update_profile_screen.dart';
export 'profile/notifications_screen.dart';
export 'profile/change_password_screen.dart';
export 'profile/support_screen.dart';
