name: scheduling_application
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies chính
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  shared_preferences: ^2.5.3

  vietqr_gen: ^1.2.0 
  qr_flutter: ^4.1.0 
  
  # Thư viện cho định dạng tiền tệ (cần thiết cho formattedPrice trong model)
  # Nếu bạn đã cài đặt thư viện này ở đâu đó, không cần thêm, 
  # nếu không, bạn nên thêm 'intl' để dùng NumberFormat
  intl: ^0.19.0 # Thêm intl nếu bạn dùng NumberFormat trong model
  localization: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Giữ lại các thư viện chỉ dùng trong quá trình phát triển (kiểm thử, lints,...)
  flutter_lints: ^5.0.0

# ... (Các phần khác giữ nguyên)
flutter:

  uses-material-design: true
# ... (Các phần còn lại)